# Generated by Django 5.1.1 on 2025-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0002_recibo_detallerecibo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerecibo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='recibo',
            old_name='total',
            new_name='saldo',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='peso_libra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='precio_libra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='tienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='tracking_id',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='wr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='total_abonos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
