# Generated by Django 5.1.1 on 2025-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0003_alter_detallerecibo_options_alter_recibo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerecibo',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Recibo', 'verbose_name_plural': 'Detalles de Recibo'},
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='peso_libra',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='precio_libra',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='peso_libras',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso en Libras'),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='precio_por_libra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por Libra'),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio del Producto'),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='saldo_producto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo del Producto'),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='total_flete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Flete'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='subtotal_flete',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo total del flete (peso × precio/lb)', max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='subtotal_productos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal de productos comprados', max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total final a pagar', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallerecibo',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Abono'),
        ),
        migrations.AlterField(
            model_name='detallerecibo',
            name='tienda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tienda'),
        ),
        migrations.AlterField(
            model_name='detallerecibo',
            name='tracking_id',
            field=models.CharField(max_length=100, verbose_name='Tracking ID'),
        ),
        migrations.AlterField(
            model_name='detallerecibo',
            name='wr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WR'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='total_abonos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total de abonos realizados', max_digits=10),
        ),
    ]
